full_file: /tmp/tmp6o9glc_5/model/model.h2o/StackedEnsemble_BestOfFamily_AutoML_20211207_144242
model_dir: /tmp/tmp6o9glc_5/model/model.h2o
model_file: StackedEnsemble_BestOfFamily_AutoML_20211207_144242
