full_file: /tmp/tmpbklvd7et/model/model.h2o/StackedEnsemble_BestOfFamily_AutoML_20211208_155427
model_dir: /tmp/tmpbklvd7et/model/model.h2o
model_file: StackedEnsemble_BestOfFamily_AutoML_20211208_155427
