artifact_uri: '"http://mlflow:5000"/4/fdc5f36963fb49d78d816f6c60faf6b2/artifacts'
end_time: 1638207412520
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: fdc5f36963fb49d78d816f6c60faf6b2
run_uuid: fdc5f36963fb49d78d816f6c60faf6b2
source_name: ''
source_type: 4
source_version: ''
start_time: 1638207380303
status: 3
tags: []
user_id: jovyan
