artifact_uri: '"http://mlflow:5000"/1/f49a85c0dcf747fdbea49a658e0d853d/artifacts'
end_time: 1638198499589
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: f49a85c0dcf747fdbea49a658e0d853d
run_uuid: f49a85c0dcf747fdbea49a658e0d853d
source_name: ''
source_type: 4
source_version: ''
start_time: 1638198467785
status: 3
tags: []
user_id: jovyan
