full_file: /tmp/tmpigx81q1b/model/model.h2o/StackedEnsemble_BestOfFamily_AutoML_20211209_100438
model_dir: /tmp/tmpigx81q1b/model/model.h2o
model_file: StackedEnsemble_BestOfFamily_AutoML_20211209_100438
