artifact_uri: '"http://mlflow:5000"/1/efc7f536f3c949b797ff2a7c22e010b7/artifacts'
end_time: 1638196835633
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: efc7f536f3c949b797ff2a7c22e010b7
run_uuid: efc7f536f3c949b797ff2a7c22e010b7
source_name: ''
source_type: 4
source_version: ''
start_time: 1638196383274
status: 3
tags: []
user_id: jovyan
