artifact_uri: '"http://mlflow:5000"/5/4bf55ba3fb814d6aacb43146bf51956e/artifacts'
end_time: 1639058625089
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 4bf55ba3fb814d6aacb43146bf51956e
run_uuid: 4bf55ba3fb814d6aacb43146bf51956e
source_name: ''
source_type: 4
source_version: ''
start_time: 1639058600374
status: 4
tags: []
user_id: jovyan
