artifact_uri: '"http://mlflow:5000"/1/d1c4aca138a844f6b1ae89420fd83def/artifacts'
end_time: 1638194734705
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d1c4aca138a844f6b1ae89420fd83def
run_uuid: d1c4aca138a844f6b1ae89420fd83def
source_name: ''
source_type: 4
source_version: ''
start_time: 1638194477504
status: 3
tags: []
user_id: jovyan
